version: 0.2

phases:
  install:
    commands:
      - echo No Node.js dependencies to install.
  build:
    commands:
      - echo Build started on `date`
      - echo Running build commands...
      # Add your actual build commands here based on your project needs
artifacts:
  files:
    - '**/*'
